# For more information: https://laravel.com/docs/sail
version: '3'
services:
    php:
        image: fredpeal/laravel-php:8.0.12
        build:
            context: ./compose/php/
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
        networks:
            - candy-suxxx
            - public-network
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'db-data:/var/lib/mysql'
        networks:
            - candy-suxxx
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - .:/var/www/
            - ./compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - candy-suxxx
            - public-network
    phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
          - 8081:80
        environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        links:
          - "mysql:db"
        depends_on:
          - mysql
        networks:
          - candy-suxxx
          - public-network
volumes:
  db-data:
  redis:

networks:
  candy-suxxx:
  public-network: